# Generated by Django 3.2 on 2021-04-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20210424_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='media_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
